import java.util.Scanner;
import java.util.Random;
/*The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number generated by the computer & involves the following steps:

The system generates a random number from a given range, say 1 to 50.
The user is prompted to enter their given number in a displayed dialogue box.
The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
The game continues under the user guessing the number.

 */

class Game {
    public int randomNumber;
    public int inputNumber;
    public int attempts = 0;

    public int getAttempts() {
        return attempts;
    }

    public void setAttempts(int attempts) {
        this.attempts = attempts;
    }

    Game() {
        Random rand = new Random();
        this.randomNumber = rand.nextInt(1,50);
    }

    void takeUserInput() {
        System.out.print("Guess the number between 0 to 50: ");
        Scanner sc = new Scanner(System.in);
        inputNumber = sc.nextInt();
    }

    boolean isCorrectNumber() {
            attempts++;

            if (inputNumber == randomNumber) {
                System.out.format("Your guessed number " + inputNumber + " is correct" + "\nYou guessed it in %d attempts \n", attempts);
                //Displaying score
                if (attempts == 1) {
                    System.out.println("Points Scored 100");
                } else if (attempts > 1 && attempts <= 4) {
                    System.out.println("Points Scored 90");
                } else if (attempts >= 5 && attempts <= 7) {
                    System.out.println("Points Scored 80");
                } else if (attempts >= 8) {
                    System.out.println("Points Scored 60");
                }
                return true;
            } else if (inputNumber < randomNumber) {
                System.out.println("Too low...");
            } else {
                System.out.println("Too high...");
            }
            return false;
    }
}
public class NumberGuessingGame {
    public static void main(String[] args) {

        Game g = new Game();
        boolean b= false;
        while(!b){
            g.takeUserInput();
            b = g.isCorrectNumber();
        }
    }
}
